#!/usr/bin/env bash
set -euxo pipefail

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# Start in /root instead of /
sed -i 's/WORKDIR=$/WORKDIR=\$HOME/' ~/.bashrc

exit 0