#!/bin/bash

# Preinstall Bolt here for now
rpm -Uvh https://yum.puppet.com/puppet-tools-release-el-7.noarch.rpm
yum install -y puppet-bolt-3.7.1

# Needed for check script
yum install -y jq

# Create the Bolt solution script file for the user
mkdir -p /root/.instruqt
cat > /root/.instruqt/configure-ntp.sh <<EOF
#!/bin/bash

# First, perform a one-time sync of the system clock if the NTP
# service is not already running
systemctl status ntpd.service >/dev/null || ntpdate -b time.apple.com

# Next, conditionally add NTP pool servers to the ntp.conf file
if ! grep -qP '^server \d+\.pool\.ntp\.org' /etc/ntp.conf; then
  echo 'server 0.pool.ntp.org' >> /etc/ntp.conf
  echo 'server 1.pool.ntp.org' >> /etc/ntp.conf
  echo 'server 2.pool.ntp.org' >> /etc/ntp.conf
  echo 'server 3.pool.ntp.org' >> /etc/ntp.conf
fi

# Finally, start or reload the NTP service
systemctl restart ntpd.service

EOF

chmod 755 /root/.instruqt/configure-ntp.sh

# Create the Bolt script file for the user to complete
grep -P '(^#|^[[:blank:]]*$)' /root/.instruqt/configure-ntp.sh > /root/configure-ntp.sh
chmod 755 /root/configure-ntp.sh

# Exit if the privacy policy has been declined by the user
[ "${INSTRUQT_PRIVACY_POLICY_CONSENT:-false}" == "false" ] && exit 1

# Install some JSON manipulation tools
yum install -y jq nodejs
npm install -g json

# Get the environment variables injected by Instruqt
printenv | grep ^INSTR | jq -sR '
    { "Env": [split("\n")[:-1][] | rtrimstr("\\r")
        | split("=") | {(.[0]): .[1]}]  | add }' > /tmp/instruqt.json

# Inject some additional JSON key/value pairs
json -I -f /tmp/instruqt.json \
    -e 'this.Env.INSTRUQT_TRACK_NAME="Build a Bolt Inventory File on Linux"' \
    -e 'this.Env.INSTRUQT_CHALLENGE_NAME="Create an inventory file and define your targets"' \
    -e 'this.Env.INSTRUQT_CHALLENGE_STATE="start"'

# Post the JSON data to the Workato endpoint
curl --max-time 10 -s -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: huds78HUIFMV8497x78bve" \
    -d @/tmp/instruqt.json \
    https://www.workato.com/webhooks/rest/15945364-35cf-4532-8fec-37447dad29d6/instruqt-lifecycle-script
