#!/bin/bash

# Perform the same commands as the user to allow skipping
mkdir /root/myproject && cd /root/myproject
bolt project init
cat<<EOF >/root/myproject/inventory.yaml
groups:
      - name: webservers
        targets:
          - web1
          - web2
        config:
          transport: ssh
    config:
      ssh:
        host-key-check: false
EOF