#!/bin/bash

set +x

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

sed -i 's/ puppet  # Added by Google/ puppet puppet.c.kmo-instruqt.internal/' /etc/hosts  # TODO: Move to bootstrap?

while  ! nc -z -w3 localhost 443
do
    echo "Waiting for port 443 to be reachable on localhost"
done

while [ -f /opt/puppetlabs/puppet/cache/state/agent_catalog_run.lock ]
do 
    echo "Waiting for agent.lock file to not exist for first agent run"
    sleep 1
done

/usr/local/bin/puppet agent -t

sleep 25

while [ -f /opt/puppetlabs/puppet/cache/state/agent_catalog_run.lock ]
do 
    echo "Waiting for agent.lock file to not exist for second agent run"
    sleep 1
done

/usr/local/bin/puppet agent -t

sleep 25

# Install some JSON manipulation tools
# NB: For this track, these need to be installed no matter what so
# we can generate an API token and use it in the check script
# Node repo moved at some point
curl -sL https://rpm.nodesource.com/setup_13.x | bash -
yum install -y jq nodejs
npm install -g json

# Generate a token to use for querying the PE APIs
type_header='Content-Type: application/json'
uri="https://puppet.c.kmo-instruqt.internal:4433/rbac-api/v1/auth/token"
data='{"login": "admin",
       "password": "puppetlabs"}'

while  ! nc -z -w3 localhost 4433
do
    echo "Waiting for port 4433 to be reachable on localhost"
done

curl --insecure --header "$type_header" --request POST "$uri" --data "$data" > /tmp/token.json

exit 0
