#!/bin/bash

# Check if the yum commands were executed properly
echo "Checking the solution of the challenge"

rpm -qa | grep -q puppet-tools-release
if [ $? -ne 0 ]; then
  fail-message "The Puppet bolt repository has not been configured"
  exit 1
fi

rpm -qa | grep -q puppet-bolt
if [ $? -ne 0 ]; then
  fail-message "Bolt has not been installed"
  exit 1
fi

exit 0