version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 2048
- name: guac2
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 2048
virtualmachines:
- name: winagent1
  image: kmo-instruqt/winagent-pe601
  machine_type: n1-highcpu-4
- name: workstation
  image: kmo-instruqt/workstation-pe601
  machine_type: n1-highcpu-4
- name: gitea
  image: kmo-instruqt/gitea-pe601
  shell: /bin/bash
  machine_type: n1-standard-8
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe601
  shell: /bin/bash
  machine_type: n1-standard-4
- name: puppet
  image: kmo-instruqt/puppet-pe601
  shell: /bin/bash
  machine_type: n1-highcpu-16
- name: nixagent2
  image: kmo-instruqt/nixagent2-pe601
  shell: /bin/bash
  machine_type: n1-standard-4
