#!/bin/bash

# Check if the yum commands were executed properly
echo "Checking the solution of the challenge"

if ! rpm -qa | grep -q puppet7-release; then
  fail-message "The Puppet package repository has not been configured"
  exit 1
fi

if ! rpm -qa | grep -q puppet-agent; then
  fail-message "The Puppet agent has not been installed"
  exit 1
fi

if ! grep PATH ~/.bashrc | grep -q /opt/puppetlabs/bin; then
  fail-message "The PATH variable does not include the path to the Puppet agent"
  exit 1
fi

if ! check-history 'source ~/.bashrc'; then
  fail-message "The ~/.bashrc file must be sourced"
  exit 1
fi

exit 0
