#!/bin/bash

# Execute the commands for the user
rpm -Uvh https://yum.puppet.com/puppet7-release-el-7.noarch.rpm
yum install -y puppet-agent
echo 'export PATH=/opt/puppetlabs/bin/:$PATH' >> ~/.bashrc
source ~/.bashrc
