#!/bin/bash

if [ "$(puppet query 'nodes { certname ~ "nixagent" }' --urls http://localhost:8080 | jq -r .[])" = '' ]; then
  fail-message "The Linux agent has not been installed yet"
  exit 1
fi

if [ "$(puppet query 'nodes { certname ~ "winagent" }' --urls http://localhost:8080 | jq -r .[])" = '' ]; then
  fail-message "The Windows agent has not been installed yet"
  exit 1
fi
