#!/bin/bash

if [ "$(puppet query 'nodes { certname ~ "nixagent" }' --urls http://localhost:8080 | jq -r .[])" = '' ]; then
  LINUX_AGENT=1
fi

if [ "$(puppet query 'nodes { certname ~ "winagent" }' --urls http://localhost:8080 | jq -r .[])" = '' ]; then
  WINDOWS_AGENT=1
fi

if [ "${LINUX_AGENT}" -o "${WINDOWS_AGENT}" ]; then
  exit 0
else
  fail-message "Neither the Linux nor the Windows agent has been installed"
  exit 1
fi
