#!/bin/bash

if [ "$(puppet query 'facts[name,value] { certname ~ "nixagent" and name = "datacenter" }' --urls http://localhost:8080 |  jq -r '.[].value.extensions.pp_datacenter' | grep -v 'null' )" != '' ]; then
  if [ "$(puppet query 'facts[name,value] { certname ~ "nixagent" and name = "role" }' --urls http://localhost:8080 |  jq -r '.[].value.extensions.pp_role' | grep -v 'null' )" != '' ]; then
    LINUX_FACT=1
  fi
fi

if [ "$(puppet query 'facts[name,value] { certname ~ "winagent" and name = "datacenter" }' --urls http://localhost:8080 |  jq -r '.[].value.extensions.pp_datacenter' | grep -v 'null' )" != '' ]; then
  if [ "$(puppet query 'facts[name,value] { certname ~ "winagent" and name = "role" }' --urls http://localhost:8080 |  jq -r '.[].value.extensions.pp_role' | grep -v 'null' )" != '' ]; then
    WINDOWS_FACT=1
  fi
fi

if [ "${LINUX_FACT}" -o "${WINDOWS_FACT}" ]; then
  exit 0
else
  fail-message "Neither the Linux nor the Windows datacenter and role fact have been created"
  exit 1
fi
