#!/bin/bash

set -x

while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

sleep 30

sed -i 's/ puppet  # Added by Google/ puppet puppet.c.kmo-instruqt.internal/' /etc/hosts  # TODO: Move to bootstrap?

IPADDR=$(hostname -I)

bolt command run "echo $IPADDR puppet puppet.c.kmo-instruqt.internal >> /etc/hosts" --no-host-key-check -u root --private-key /root/.ssh/id_rsa --targets nixagent1,nixagent2

bolt command run "Add-Content -Value '$IPADDR puppet puppet.c.kmo-instruqt.internal' -Path C:\Windows\System32\drivers\etc\hosts" --no-ssl-verify --user Administrator --password Puppetlabs! --targets winrm://winagent

bolt command run 'curl --insecure https://puppet.c.kmo-instruqt.internal:8140/packages/current/install.bash | bash -s custom_attributes:challengePassword=PASSWORD_FOR_AUTOSIGNER_SCRIPT; timedatectl set-timezone America/Los_Angeles' --no-host-key-check -u root --private-key /root/.ssh/id_rsa --targets nixagent1,nixagent2

bolt command run 'Restart-Service puppet' --no-ssl-verify --user Administrator --password Puppetlabs! --targets winrm://winagent

bolt command run 'tzutil /s "Eastern Standard Time"' --no-ssl-verify --user Administrator --password Puppetlabs! --targets winrm://winagent

sleep 10

/usr/local/bin/puppet agent -t

sleep 25

# Set datacenter fact on winagent 
bolt command run 'New-Item -Type File -Path C:\ProgramData\PuppetLabs\Facter\facts.d\datacenter.ps1' --no-ssl-verify --user Administrator --password Puppetlabs! --targets winrm://winagent
bolt command run "Set-Content -Value 'Write-Host "datacenter=datacenter-east"' -Path C:\ProgramData\PuppetLabs\Facter\facts.d\datacenter.ps1" --no-ssl-verify --user Administrator --password Puppetlabs! --targets winrm://winagent


# Generate a token to use with puppet job run
type_header='Content-Type: application/json'
uri="https://$(puppet config print server):4433/rbac-api/v1/auth/token"
data='{"login": "admin",
       "password": "puppetlabs"}'

while ! nc -z -w3 localhost 4433
do
  echo "Waiting for port 4433 to be reachable on localhost"
done

curl --insecure --header "$type_header" --request POST "$uri" --data "$data" > /tmp/token.json
mkdir -p /root/.puppetlabs
cat /tmp/token.json | jq -r .token > /root/.puppetlabs/token
chmod 600 /root/.puppetlabs/token

# Now run Puppet twice on the nodes
# puppet job run --query 'nodes {}'
# puppet job run --query 'nodes {}'


# setup webhook on gitea server with RBAC token
curl -XPOST -H "Content-Type: application/json" \
  -u puppet:puppetlabs \
  -d "{\"type\": \"gitea\", \"config\": {\"content_type\": \"json\",\"url\": \"https://$(hostname):8170/code-manager/v1/webhook?type=github\u0026token=$(cat /root/.puppetlabs/token)\"},\"events\": [\"push\"],\"active\": true}" \
  http://gitea:3000/api/v1/repos/puppet/control-repo/hooks
